### ISSUE TITLE
Integrate with Rando Map Mod S

### ISSUE THREAD

**Issue by Ijwu** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#15]
Research how Randomizer Map Mod S works and see if it is possible to integrate with it.

**Comment by KonoTyran** [comment]
I've looked at the code of RMMS and it seems to hook directly into rando 4 for some portions of it. Looks like we would have to fork it and make a version specifically for AP.

It also seems that #1 should be resolved before this as this will have to change depending on the method of implementation of #1.

I may look into getting a non logic tracking version of RMMS to start with. Just so we can have something. And its a good excuse to branch into C# stuff.

**Comment by BadMagic100** [comment]
I think the above is a viable approach. In the long term it's probably worth seeing if Phenomenol is willing to try to make this into a more generalized "ItemChanger Map Mod" with plugin support (e.g. rather than having RandoMapMod do everything it does today, ICMM would be responsible for placing pins, tracking whether an item is obtained, etc; while RMM would be a lightweight plugin that handles additional rando-specific features like logic tracking and room rando route finding)

I currently own ConnectionMetadataInjector/CMICore which is a mod that supports injecting data via itemchanger tags (i.e. as a soft dependency), which RMM uses to determine which pin is used for a given location. Currently it's pretty coupled to rando as well but I'd be glad to try and decouple it if stuff ends up going this route (e.g. this could support archipelago injecting a custom pin sprite to use on the map for previewed/spoilered remote items)

**Comment by Ijwu** [comment]
I'll be sure to chat with Phenomenol about this soon.
