### ISSUE TITLE
Optional Extra Platforms for Player Convenience

### ISSUE THREAD

**Issue by Ijwu** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#58]
Some platform additions to the map may be necessary to enable feasibility for certain logic options. I do not know what these platforms are nor where they would go. This requires investigation to determine the correct platforms and their placement. 

Here is a good place to start looking: https://github.com/homothetyhk/RandomizerMod/blob/master/RandomizerMod/IC/PlatformList.cs

**Comment by Ijwu** [comment]
Apparently the most logically relevant platforms are a default module in ItemChanger which means they are enabled automatically in Archipelago.HollowKnight. Adjusting this issue to cover **optional** extra platforms now.

**Comment by dewiniaid** [comment]
Extra platforms are never strictly required since Benchwarp exists, though they definitely add convenience.

They mostly cover things that are 2-way in vanilla but are only 1-way in rando due to logic -- i.e. you can logically reach Mantis Lords with just wings (or potentially just left claw?) but there is no way back out without platforms being added, so if you reach the scene without right claw a way to jump back out is added.  This avoids what would be a softlock without Benchwarp, but does not hinder progression at all.  (Quite possibly why they can be turned off)

I'm curious about which ones are automatically added by IC other than RightCityPlatform.  I'm not sure if any others are from peeking through it, it just presents the ability to add them -- in which case we'd probably want to adopt most if not all of Rando4's platforms and logic.

**Comment by BadMagic100** [comment]
Will work on this for next release. Will need to investigate the full list of platforms rando creates, but most notably I will be adding platforms at:

* Basin platforms (broken bridge, dive grub)
* Waterways grub
* Howling Cliffs
* Petra Arena Gate
* Mantis Lords (if we can prevent OoL access to the lifeblood with left cheart even better)
* Deepnest mimics (interior and exterior, includes geo rocks)
* Colosseum bench
* Dirtmouth to KP
* Goam Journal exit (not in rando4, but requested)

The solution here should be plug-and-play enough that platforms can easily be added depending on start location settings (#134) and transition rando settings (#35) once implemented

**Comment by BadMagic100** [comment]
This should probably have a corresponding setting, so holding until we have a server-side maintainer

**Comment by Ijwu** [comment]
I would suggest that configs which do not affect logic might be best configured within the Hollow Knight mod. This and #157 are not necessarily logic altering (to my knowledge) and might not require a server-side implementer.

Although I understand holding off on heavy work until one is found.

**Comment by BadMagic100** [comment]
I think having all the options in one place is generally going to be more convenient and intuitive to players. There are already settings which don't affect logic such as shade handling for deathlink included in the slot options

**Comment by Ijwu** [comment]
I agree that having all settings in one place is generally more convenient. I would not agree that AP's options system via YAML files is "intuitive". 

Perhaps you should move non-logic based settings, such as shade handling, into the client mod to preface this? It could be a first-time connection menu (on save file creation) or it could be a menu each time they load into the slot, allowing for differing settings per session. Generally, I think AP users are understanding enough to know that some settings belong in one place and some settings might be present in others.

Having an interface in Hollow Knight for some options will _always_ be more convenient and intuitive than YAML file editing.

**Comment by BadMagic100** [comment]
For non-numeric options I think the web interface that people typically use for settings creation is pretty reasonable

**Comment by dewiniaid** [comment]
I feel that non-logic gameplay-affecting settings definitely belong in the
YAML for one reason alone: protecting the integrity of race seeds.

(Despite this, I feel there should be a toggle for Deathlink in-game
because there's a possibility of somebody wanting to change their mind
mid-run... Like if they didn't realize another player was playing SA2B)

**Comment by BadMagic100** [comment]
Yeah I did notice that but undoing the FSM edits is cursed. It's on my radar but idk if I want to deal with it

**Comment by ThePhar** [comment]
https://github.com/ArchipelagoMW/Archipelago/pull/2545
